version: '2'
services:
  jm-app:
    image: app
    container_name: application
    ports:
      - "8080:8080"
    depends_on:
      - jm-postgres
  jm-postgres:
    image: postgres:10.1
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=Rikimarolox123
      - POSTGRES_USER=root
      - POSTGRES_DB=user